ruleset:
  label_bugs:
    name: "Label issues as bug"
    events: [ issues ]
    label: bug
    when:
      - body contains "[x] Bug"
      - action = "opened" or action = "reopened"

  missing_version:
    name: "Close bugs with missing version number"
    events: [ issues ]
    close: true
    label: invalid
    message: >
      @{{ user.login }}, please re-open once you have added
      the version you are using per our contributing guidelines.
    when:
      - action = "labelled"
      - filter(labels, "name") has "bug"
      - not (body matches "/[0-9]{1,2}\.[0-9]+(\.[0-9]+)?/")

  short_description:
    name: "Close issues with short descriptions"
    events: [ issues, pull_request ]
    close: true
    label: invalid
    when: length(body) < 50

  remove_invalid:
    name: "Remove invalid tag when issue re-opened"
    events: [ issues, pull_request ]
    label: -invalid
    when:
      - action = "reopened"
      - filter(labels, "name") has "invalid"

  auto_merge:
    name: "Automatically merge certain pull requests"
    events: [ pull_request ]
    merge: true
    when:
      - action = "reopened"
      - filter(labels, "name") has "invalid"